server {
    listen       80;
    listen  [::]:80;
    server_name 8.210.214.167;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html?$query_string;
        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Max-Age 1728000;
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, DELETE';
        add_header Access-Control-Allow-Headers 'Authorization, Content-Type, Depth,User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, X-File-Type, Cache-Control, Origin';
    }

    location /okex/ {
        proxy_pass http://8.210.214.167:8090/;
        proxy_cookie_domain 8.210.214.167:8090 8.210.214.167;
        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS';
    }

    location /okexSwap/ {
        proxy_pass http://8.210.214.167:8091/;
        proxy_cookie_domain 8.210.214.167:8091 8.210.214.167;
        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS';
    }

     location /bn/ {
        proxy_pass http://8.210.214.167:8092/;
        proxy_cookie_domain 8.210.214.167:8092 8.210.214.167;
        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS';
     }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

}
